# Generated by Django 5.2.4 on 2025-07-31 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='medium', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='starred',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
