# Generated by Django 5.2.4 on 2025-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_created_todo_priority_todo_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='todo',
            name='starred',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
