# Generated by Django 5.2.4 on 2025-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_by',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
